title: BIOL3062 textbook
description: A Brief Introduction to Behavioural Ecology
theme: just-the-docs

url: https://binohead.github.io/textbook

aux_links:
  Template Repository: https://github.com/binohead/textbook
